# Generated by Django 5.0.4 on 2026-08-30 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_classroom_table_alter_school_table_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroom',
            name='unique_classroom_per_school',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_room',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='class_rooms',
            new_name='classrooms',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='apis.school'),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms',
        ),
    ]
